apiVersion:apps/v1
kind:Deployment
metadata:
  name:worker-deployment
spec:
  replicas:1
  selector:
  matchLabels:
    componet:worker
  template:
   metadata:
    Labels: 
     componeny:worker
  spec:
   containers:
   -name:worker
   image:stephengrinder/multi-worker     
   env:
    -name:REDIS_HOST
    value:redis-custer-ip-service
    -name:REDIS_PORT
     value:6379 
  